language: rust

cache:
  - cargo

before_deploy:
  - cargo doc
  - mkdir public
  - cp -r target/doc public/
  - pwd
  - ls
  - echo "<meta http-equiv=refresh content=0;url=book/html/index.html>" > public/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: main
