name: Cargo CI Checks
on:
  - push:
    branches:
      - main
  - pull_request:
jobs:
  cargo_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: rustfmt clippy
            override: true
      - name: setup
        run: |
          rustup component add rustfmt clippy
          rustc --version
      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          toolchain: nightly
          args: --check
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: cargo-check
        uses: actions-rs/cargo@v1
        with:
          command: check
